name: Deploy Serverless Function

on:
  workflow_dispatch

env:
  NODE_VER: '18.x'
  MONGO_ATLAS_URL: ${{ secrets.MONGO_ATLAS_URL_PROD }}

jobs:
  mainbuild:
    name: CI on Ubuntu 22.04
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: 'auth'
        name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          workload_identity_provider: projects/345207492413/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-oidc
          service_account: 'assignment-6-workflow@peerprep-group11-prod.iam.gserviceaccount.com'

      # Setup gcloud CLI
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VER }}

      - name: Clean Install dependencies
        run: npm ci

      - name: Deploy Serverless
        run: serverless deploy
