name: Deploy Serverless Function

on:
  workflow_dispatch

env:
  NODE_VER: '18.x'
  MONGO_ATLAS_URL: ${{ secrets.MONGO_ATLAS_URL_PROD }}

jobs:
  mainbuild:
    name: Deploy serverless function on Ubuntu 22.04
    runs-on: ubuntu-22.04
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: 'auth'
        name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: projects/345207492413/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-oidc
          service_account: 'assignment-6-workflow@peerprep-group11-prod.iam.gserviceaccount.com'

      - id: 'deploy'
        name: Deploy the cloud function
        uses: 'google-github-actions/deploy-cloud-functions@v1'
        with:
          name: 'fetchAndStoreDailyQuestion'
          runtime: 'nodejs18'
          region: 'asia-southeast1'
          project_id: 'peerprep-group11-prod'
          entry_point: httpHandler
          env_vars:
            MONGO_ATLAS_URL=${{ secrets.MONGO_ATLAS_URL_PROD }}

      - id: 'authAgain'
        name: Re-authenticate to Google Cloud, this time grabbing id_token
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'id_token'
          id_token_audience: ${{ steps.deploy.outputs.url }}
          workload_identity_provider: projects/345207492413/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-oidc
          service_account: 'assignment-6-workflow@peerprep-group11-prod.iam.gserviceaccount.com'

      # Example of using the output
      - id: 'test'
        name: Run a curl test
        run: |-
          curl "${{ steps.deploy.outputs.url }}" \
            -H "Authorization: bearer ${{ steps.authAgain.outputs.id_token }}" \
            -H "Content-Type: application/json" \
            -d '{}'
